package no.nav.syfo.huskelapp.domain

enum class Oppfolgingsgrunn {
    TA_KONTAKT_SYKEMELDT,
    TA_KONTAKT_ARBEIDSGIVER,
    TA_KONTAKT_BEHANDLER,
    VURDER_DIALOGMOTE_SENERE,
    FOLG_OPP_ETTER_NESTE_SYKMELDING,
    VURDER_TILTAK_BEHOV,
    VURDER_ARBEIDSUTFORHET,
    FRISKMELDING_TIL_ARBEIDSFORMIDLING,
    ANNET,
}
