ALTER TABLE HUSKELAPP_VERSJON ADD COLUMN IF NOT EXISTS latest BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE HUSKELAPP_VERSJON SET latest = TRUE WHERE ID IN (SELECT MAX(ID) FROM HUSKELAPP_VERSJON GROUP BY huskelapp_id);

CREATE INDEX IF NOT EXISTS IX_HUSKELAPP_VERSJON_LATEST on HUSKELAPP_VERSJON (huskelapp_id) WHERE latest = TRUE;
